global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: 'lazyjobfinder'
    static_configs:
      - targets: ['localhost:4000']  # Assuming lazyjobfinder exposes metrics at port 4000
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
